count: 100

corpus:
  paths: [resources/corpus/financial_corpus.txt]
  weights: [1]
  min_length: 1
  max_length: 25
  textcase: [lower, upper, capitalize]

font:
  paths: [resources/font]
  weights: [1]
  size: [11, 26]
  bold: 0.35

color:
  rgb: [[0, 0], [0, 0], [0, 0]]
  alpha: [.15, 1]
  grayscale: 0

layout:
  length: [1024, 1024]
  space: [8, 20]
  line_space: [0, 16]
  align: [left, center, right, justify]
  line_align: [middle]
  ltr: false
  ttb: true
  vertical: false
